import {
  BsTrash,
  BsGear,
  BsPerson,
  BsSearch,
  BsPeople,
  BsList,
  BsBell,
  BsQuestionCircle,
  BsHouseDoor,
  BsBook,
  BsBox,
  BsGlobe,
  BsUpload,
  BsBagCheck,
  BsPlusSquare,
  BsPlusLg,
  BsChevronDown,
  BsChevronRight,
  BsStar,
  BsBorderAll,
} from "react-icons/bs";

export const Icons = {
  Add: BsPlusLg,
  AddSquare: BsPlusSquare,
  Airtable: BsBox,
  Bell: BsBell,
  Book: BsBook,
  Box: BsBorderAll,
  Down: BsChevronDown,
  Globe: BsGlobe,
  Help: BsQuestionCircle,
  Home: BsHouseDoor,
  Marketplace: BsBagCheck,
  Menu: BsList,
  People: BsPeople,
  Person: BsPerson,
  Right: BsChevronRight,
  Search: BsSearch,
  Settings: BsGear,
  Star: BsStar,
  Trash: BsTrash,
  Import: BsUpload,
};
