import {
  BsTrash,
  BsGear,
  BsPerson,
  BsSearch,
  BsPeople,
  BsList,
  BsBell,
  BsQuestionCircle,
  BsHouseDoor,
  BsBook,
  BsBox,
  BsGlobe,
  BsUpload,
  BsBagCheck,
  BsPlusSquare,
  BsPlusLg,
  BsChevronDown,
  BsChevronRight,
  BsStar,
  BsBorderAll,
  BsThreeDots,
  BsClockHistory,
  BsTable,
  BsEyeSlash,
  BsFilter,
  BsCardChecklist,
  BsArrowDownUp,
  BsPaintBucket,
  BsArrowsVertical,
  BsTextParagraph,
  BsBoxArrowUpRight,
  BsCheck2,
  BsCalendar2Date,
  BsGrid,
  BsKanban,
  BsBarChartSteps,
  BsSliders,
  BsCardHeading,
} from "react-icons/bs";

export const Icons = {
  Add: BsPlusLg,
  AddSquare: BsPlusSquare,
  Airtable: BsBox,
  ArrowsVertical: BsArrowsVertical,
  Bell: BsBell,
  Book: BsBook,
  Box: BsBorderAll,
  Check: BsCheck2,
  Calendar: BsCalendar2Date,
  Color: BsPaintBucket,
  Down: BsChevronDown,
  Filter: BsFilter,
  Form: BsCardHeading,
  Gallery: BsGrid,
  Gantt: BsSliders,
  Globe: BsGlobe,
  Group: BsCardChecklist,
  Help: BsQuestionCircle,
  Hide: BsEyeSlash,
  History: BsClockHistory,
  Home: BsHouseDoor,
  Kanban: BsKanban,
  Text: BsTextParagraph,
  Timeline: BsBarChartSteps,
  Marketplace: BsBagCheck,
  Menu: BsList,
  People: BsPeople,
  Person: BsPerson,
  Right: BsChevronRight,
  Share: BsBoxArrowUpRight,
  Search: BsSearch,
  Settings: BsGear,
  Sort: BsArrowDownUp,
  Star: BsStar,
  Table: BsTable,
  Trash: BsTrash,
  ThreeDots: BsThreeDots,
  Import: BsUpload,
};
